### ISSUE TITLE
Hello from the old AssemblyLine developer

### ISSUE THREAD

**Issue by DarkGuardsman** [aurilisdev/Assembly-Line#2]
Not sure if we have chatted before but someone reached out to me recently. They let me know you're reviving a lot of the old mods I developed. Want to check in that you have not recycled any of the old code or assets. If you have any old code it will need to be under MIT license and any assets would require permission from the original artists. This way you avoid any confusing copyright issues. 

Other than that good job on keeping these old projects alive. I have not been able to do it myself so am happy to see them recreated with new life. Let me know if you need anything.

**Comment by aurilisdev** [comment]
I dont use your old code or assets :)

**Comment by DarkGuardsman** [comment]
Good :) look forward to seeing how these mods evolve under your development

**Comment by aurilisdev** [comment]
Im glad you think that though :) I will let you know if i need anything
