### ISSUE TITLE
The Autocrafter has a bigger hitbox(?) than implied and is missing texture data

### ISSUE THREAD

**Issue by 9thCore** [aurilisdev/Assembly-Line#39]
The autocrafter has two sides (its west and north) where you get pushed out a block from the model, and particles and head-inside-block textures are missing
check video for more info

Video:
https://github.com/aurilisdev/Assembly-Line/assets/38700349/71903b9b-5566-4381-ba94-a191b71993fc

Log:
https://hastebin.com/share/ilanuzoheg.csharp

Instance info:
Tested on a singleplayer server
Forge 47.3.0
Electrodynamics 1.20.1-0.9.0-4
Assembly Line 1.20.1-0.6.0-3
(no other mods)

**Comment by skiprocks999** [comment]
This will be fixed in the next update for 1.20.1
