### ISSUE TITLE
java.lang.NoClassDefFoundError when starting modpack

### ISSUE THREAD

**Issue by zaze06** [aurilisdev/Assembly-Line#5]
So im making a modpack that i whant to have assembly line in but the mod cant load correctly. crash log provided as attach [file](https://github.com/aurilisdev/Assembly-Line/files/7192574/crash-2021-09-19_19.18.42-fml.txt)

**Comment by zaze06** [comment]
ok, I mist to add Electrodynamics mod but can you add it as a dependency?

**Comment by aurilisdev** [comment]
In the newest code this has already been done

**Comment by zaze06** [comment]
i meant in curseforge

**Comment by aurilisdev** [comment]
Yes i set it automatically in the code. I never upload manually

**Comment by zaze06** [comment]
o ok i didn't know that was even possible but thx :)
